<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>AIPort</AssemblyName>
    <RootNamespace>AIPort</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
    <DebugType>portable</DebugType>
    <OutputPath>$(MSBuildThisFileDirectory)..\..\artifacts\bin\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="TaleWorlds.MountAndBlade">
      <HintPath>$(BannerlordClientBin)\TaleWorlds.MountAndBlade.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.Library">
      <HintPath>$(BannerlordClientBin)\TaleWorlds.Library.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.CampaignSystem.ViewModelCollection">
      <HintPath>$(BannerlordClientBin)\TaleWorlds.CampaignSystem.ViewModelCollection.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.ScreenSystem">
      <HintPath>$(BannerlordClientBin)\TaleWorlds.ScreenSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SandBox.View">
      <HintPath>$(BannerlordClientBin)\..\..\Modules\SandBox\bin\Win64_Shipping_Client\SandBox.View.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Common">
      <HintPath>$(CoopClientBin)\Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Coop.Core">
      <HintPath>$(CoopClientBin)\Coop.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="GameInterface">
      <HintPath>$(CoopClientBin)\GameInterface.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Serilog">
      <HintPath>$(CoopClientBin)\Serilog.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="protobuf-net">
      <HintPath>$(CoopClientBin)\protobuf-net.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="protobuf-net.Core">
      <HintPath>$(CoopClientBin)\protobuf-net.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="LiteNetLib">
      <HintPath>$(CoopClientBin)\LiteNetLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
