using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
namespace AIPort.Server
{
    public sealed class AIPortStateStore
    {
        private readonly object gate=new object();private readonly bool enabled;private readonly string root;
        private string campaignId=string.Empty,saveName=string.Empty,generation=string.Empty,lastCampaignTime=string.Empty;private long revision;private bool loaded,readOnly,saving;
        public AIPortStateStore(bool enabled,string root){this.enabled=enabled&&!string.IsNullOrWhiteSpace(root);this.root=string.IsNullOrWhiteSpace(root)?string.Empty:Path.GetFullPath(root);}
        public bool Enabled{get{return enabled;}}public bool Loaded{get{lock(gate)return loaded;}}public bool ReadOnly{get{lock(gate)return readOnly;}}public bool IsSaving{get{lock(gate)return saving;}}public string CampaignGeneration{get{lock(gate)return generation;}}public long Revision{get{lock(gate)return revision;}}
        public void BeginLoad(string loadedSaveName,string uniqueCampaignId){lock(gate){saveName=Normalize(loadedSaveName);campaignId=Normalize(uniqueCampaignId);generation=ComputeGeneration(campaignId,saveName);lastCampaignTime=string.Empty;revision=0;loaded=false;readOnly=false;saving=false;}}
        public string LoadAfterObjectsRegistered(string campaignTime,ConversationMemory memory,SocialShadowLedger social,DiplomaticStatementLedger diplomacy){return LoadAfterObjectsRegistered(campaignTime,memory,social,diplomacy,null);}
        public string LoadAfterObjectsRegistered(string campaignTime,ConversationMemory memory,SocialShadowLedger social,DiplomaticStatementLedger diplomacy,NativeDiplomacyCommitJournal nativeJournal)
        {
            if(!enabled){lock(gate){loaded=true;revision=memory.Revision;}return "disabled";}
            string dir,gen,cid,sn;lock(gate){cid=campaignId;sn=saveName;gen=generation;if(cid.Length==0||sn.Length==0||gen.Length==0){readOnly=true;loaded=false;return "identity_missing";}dir=GenerationDirectory(cid,gen);}
            try
            {
                string manifestPath=Path.Combine(dir,"manifest.json"),memoryPath=Path.Combine(dir,"memory.ndjson"),socialPath=Path.Combine(dir,"social.ndjson"),diplomacyPath=Path.Combine(dir,"diplomacy.ndjson");
                if(!File.Exists(manifestPath)){Directory.CreateDirectory(dir);social.Clear();diplomacy.Clear();if(nativeJournal!=null)nativeJournal.Clear();lock(gate){loaded=true;readOnly=false;revision=memory.Revision;lastCampaignTime=campaignTime??string.Empty;}return "new_generation";}
                string manifest=File.ReadAllText(manifestPath,Encoding.UTF8);if(ReadInt(manifest,"schema",0)!=1||!string.Equals(Read(manifest,"generation"),gen,StringComparison.Ordinal)){lock(gate){readOnly=true;loaded=false;}return "manifest_mismatch";}
                string savedCampaign=FromB64(Read(manifest,"campaign")),savedName=FromB64(Read(manifest,"save")),savedTime=FromB64(Read(manifest,"campaignTime"));
                if(!string.Equals(savedCampaign,cid,StringComparison.Ordinal)||!string.Equals(savedName,sn,StringComparison.Ordinal)||!string.Equals(savedTime,campaignTime??string.Empty,StringComparison.Ordinal)){lock(gate){readOnly=true;loaded=false;}return "save_generation_mismatch";}
                string data=File.Exists(memoryPath)?File.ReadAllText(memoryPath,Encoding.UTF8):string.Empty;if(!string.Equals(Read(manifest,"memorySha256"),AIPortStateCodec.Sha256(data),StringComparison.Ordinal)){lock(gate){readOnly=true;loaded=false;}return "memory_hash_mismatch";}
                string socialData=File.Exists(socialPath)?File.ReadAllText(socialPath,Encoding.UTF8):string.Empty,expectedSocialHash=Read(manifest,"socialSha256");
                if((expectedSocialHash.Length>0&&!string.Equals(expectedSocialHash,AIPortStateCodec.Sha256(socialData),StringComparison.Ordinal))||(expectedSocialHash.Length==0&&socialData.Length>0)){lock(gate){readOnly=true;loaded=false;}return "social_hash_mismatch";}
                string diplomacyData=File.Exists(diplomacyPath)?File.ReadAllText(diplomacyPath,Encoding.UTF8):string.Empty,expectedDiplomacyHash=Read(manifest,"diplomacySha256");
                if((expectedDiplomacyHash.Length>0&&!string.Equals(expectedDiplomacyHash,AIPortStateCodec.Sha256(diplomacyData),StringComparison.Ordinal))||(expectedDiplomacyHash.Length==0&&diplomacyData.Length>0)){lock(gate){readOnly=true;loaded=false;}return "diplomacy_hash_mismatch";}
                List<PersistentMemoryRecord> records=AIPortStateCodec.ParseLines(data);List<PersistentSocialRecord> socialRecords=expectedSocialHash.Length==0?new List<PersistentSocialRecord>():AIPortStateCodec.ParseSocialLines(socialData);List<PersistentDiplomaticStatementRecord> diplomacyRecords=expectedDiplomacyHash.Length==0?new List<PersistentDiplomaticStatementRecord>():AIPortStateCodec.ParseDiplomacyLines(diplomacyData);memory.ImportPersistentRecords(records);social.Import(socialRecords);diplomacy.Import(diplomacyRecords);string journalReason=LoadNativeJournalFiles(dir,nativeJournal);if(journalReason!="native_journal_loaded"){lock(gate){readOnly=true;loaded=false;}return journalReason;}memory.AdvanceRevision(socialRecords.Count+diplomacyRecords.Count);lock(gate){revision=memory.Revision;loaded=true;readOnly=false;lastCampaignTime=savedTime;}return "loaded:"+records.Count.ToString(CultureInfo.InvariantCulture)+":social:"+socialRecords.Count.ToString(CultureInfo.InvariantCulture)+":diplomacy:"+diplomacyRecords.Count.ToString(CultureInfo.InvariantCulture)+":nativeJournal:"+(nativeJournal==null?0:nativeJournal.Count).ToString(CultureInfo.InvariantCulture);
            }catch(Exception ex){lock(gate){readOnly=true;loaded=false;}return "load_failed:"+ex.GetType().Name;}
        }
        public void BeginSaveBarrier(){lock(gate)saving=true;}
        public string Save(string savedSaveName,string uniqueCampaignId,string campaignTime,ConversationMemory memory,SocialShadowLedger social,DiplomaticStatementLedger diplomacy){return Save(savedSaveName,uniqueCampaignId,campaignTime,memory,social,diplomacy,null);}
        public string Save(string savedSaveName,string uniqueCampaignId,string campaignTime,ConversationMemory memory,SocialShadowLedger social,DiplomaticStatementLedger diplomacy,NativeDiplomacyCommitJournal nativeJournal)
        {
            if(!enabled)return "disabled";string observedCid=Normalize(uniqueCampaignId),observedSn=Normalize(savedSaveName),cid,sn,gen;lock(gate){if(readOnly)return "read_only";cid=campaignId;sn=saveName;gen=generation;if(cid.Length==0||sn.Length==0||gen.Length==0){cid=observedCid;sn=observedSn;gen=ComputeGeneration(cid,sn);campaignId=cid;saveName=sn;generation=gen;}}if(cid.Length==0||sn.Length==0||gen.Length==0)return "identity_missing";
            try
            {
                List<PersistentMemoryRecord> records=memory.ExportPersistentRecords(null);List<PersistentSocialRecord> socialRecords=social.Export(null);List<PersistentDiplomaticStatementRecord> diplomacyRecords=diplomacy.Export(null);string data=AIPortStateCodec.SerializeLines(records),socialData=AIPortStateCodec.SerializeSocialLines(socialRecords),diplomacyData=AIPortStateCodec.SerializeDiplomacyLines(diplomacyRecords);string dir=GenerationDirectory(cid,gen);Directory.CreateDirectory(dir);WriteAtomic(Path.Combine(dir,"memory.ndjson"),data);WriteAtomic(Path.Combine(dir,"social.ndjson"),socialData);WriteAtomic(Path.Combine(dir,"diplomacy.ndjson"),diplomacyData);WriteNativeJournalFiles(dir,nativeJournal);long rev=memory.Revision;
                string manifest="{\"schema\":1,\"campaign\":\""+B64(cid)+"\",\"save\":\""+B64(sn)+"\",\"generation\":\""+gen+"\",\"campaignTime\":\""+B64(campaignTime??string.Empty)+"\",\"revision\":"+rev.ToString(CultureInfo.InvariantCulture)+",\"memorySha256\":\""+AIPortStateCodec.Sha256(data)+"\",\"recordCount\":"+records.Count.ToString(CultureInfo.InvariantCulture)+",\"socialSha256\":\""+AIPortStateCodec.Sha256(socialData)+"\",\"socialRecordCount\":"+socialRecords.Count.ToString(CultureInfo.InvariantCulture)+",\"diplomacySha256\":\""+AIPortStateCodec.Sha256(diplomacyData)+"\",\"diplomacyRecordCount\":"+diplomacyRecords.Count.ToString(CultureInfo.InvariantCulture)+",\"savedUtc\":\""+DateTime.UtcNow.ToString("o",CultureInfo.InvariantCulture)+"\"}";
                WriteAtomic(Path.Combine(dir,"manifest.json"),manifest);lock(gate){revision=rev;loaded=true;readOnly=false;lastCampaignTime=campaignTime??string.Empty;}return "saved:"+records.Count.ToString(CultureInfo.InvariantCulture)+":social:"+socialRecords.Count.ToString(CultureInfo.InvariantCulture)+":diplomacy:"+diplomacyRecords.Count.ToString(CultureInfo.InvariantCulture);
            }catch(Exception ex){lock(gate)readOnly=true;return "save_failed:"+ex.GetType().Name;}
        }
        public void EndSaveBarrier(){lock(gate)saving=false;}
        public bool TryBuildPrivateSnapshot(ConversationMemory memory,SocialShadowLedger social,DiplomaticStatementLedger diplomacy,string playerHeroId,out string json,out string hash,out string reason)
        {
            json=string.Empty;hash=string.Empty;reason=string.Empty;lock(gate){if(!loaded){reason="state_not_loaded";return false;}if(readOnly){reason="state_read_only";return false;}}
            try{json=AIPortStateCodec.SerializeSnapshot(memory.ExportPersistentRecords(playerHeroId),social.Export(playerHeroId),diplomacy.Export(playerHeroId));hash=AIPortStateCodec.Sha256(json);return true;}catch(Exception ex){reason="snapshot_failed:"+ex.GetType().Name;return false;}
        }
        public bool PersistNativeJournal(NativeDiplomacyCommitJournal journal,out string reason)
        {reason="native_journal_unavailable";string dir;lock(gate){if(!enabled||!loaded||readOnly||saving||string.IsNullOrWhiteSpace(campaignId)||string.IsNullOrWhiteSpace(generation))return false;dir=GenerationDirectory(campaignId,generation);}try{WriteNativeJournalFiles(dir,journal);reason="native_journal_persisted";return true;}catch(Exception ex){lock(gate)readOnly=true;reason="native_journal_persist_failed:"+ex.GetType().Name;return false;}}
        public void EnterReadOnly(){lock(gate)readOnly=true;}
        private static void WriteNativeJournalFiles(string dir,NativeDiplomacyCommitJournal journal){if(journal==null)return;string data=AIPortStateCodec.SerializeNativeDiplomacyJournalLines(journal.Export());WriteAtomic(Path.Combine(dir,"native-diplomacy-journal.ndjson"),data);WriteAtomic(Path.Combine(dir,"native-diplomacy-journal.sha256"),AIPortStateCodec.Sha256(data));}
        private static string LoadNativeJournalFiles(string dir,NativeDiplomacyCommitJournal journal){if(journal==null)return "native_journal_loaded";string dataPath=Path.Combine(dir,"native-diplomacy-journal.ndjson"),hashPath=Path.Combine(dir,"native-diplomacy-journal.sha256");if(!File.Exists(dataPath)&&!File.Exists(hashPath)){journal.Clear();return "native_journal_loaded";}if(!File.Exists(dataPath)||!File.Exists(hashPath))return "native_journal_incomplete";string data=File.ReadAllText(dataPath,Encoding.UTF8),expected=File.ReadAllText(hashPath,Encoding.UTF8).Trim();if(!string.Equals(expected,AIPortStateCodec.Sha256(data),StringComparison.Ordinal))return "native_journal_hash_mismatch";List<PersistentNativeDiplomacyCommitRecord> records=AIPortStateCodec.ParseNativeDiplomacyJournalLines(data);int nonEmptyLines=0;foreach(string line in data.Split(new[]{'\r','\n'},StringSplitOptions.RemoveEmptyEntries))nonEmptyLines++;if(records.Count!=nonEmptyLines)return "native_journal_parse_failed";journal.Import(records);if(journal.Count!=records.Count)return "native_journal_parse_failed";return "native_journal_loaded";}
        private string GenerationDirectory(string cid,string gen){return Path.Combine(root,"campaigns",AIPortStateCodec.Sha256(cid).Substring(0,32),gen);}
        private static string ComputeGeneration(string cid,string sn){return cid.Length==0||sn.Length==0?string.Empty:AIPortStateCodec.Sha256(cid+"|"+sn).Substring(0,32);}
        private static void WriteAtomic(string path,string text){string temp=path+".tmp";byte[] bytes=new UTF8Encoding(false).GetBytes(text??string.Empty);using(FileStream f=new FileStream(temp,FileMode.Create,FileAccess.Write,FileShare.None)){f.Write(bytes,0,bytes.Length);f.Flush(true);}if(File.Exists(path))File.Replace(temp,path,path+".bak",true);else File.Move(temp,path);}
        private static string Read(string json,string key){string n="\""+key+"\":";int i=json.IndexOf(n,StringComparison.Ordinal);if(i<0)return string.Empty;i+=n.Length;while(i<json.Length&&char.IsWhiteSpace(json[i]))i++;if(i>=json.Length||json[i]!='\"')return string.Empty;i++;int e=json.IndexOf('\"',i);return e<0?string.Empty:json.Substring(i,e-i);}
        private static int ReadInt(string json,string key,int fallback){string n="\""+key+"\":";int i=json.IndexOf(n,StringComparison.Ordinal);if(i<0)return fallback;i+=n.Length;while(i<json.Length&&char.IsWhiteSpace(json[i]))i++;int e=i;while(e<json.Length&&char.IsDigit(json[e]))e++;int v;return e>i&&int.TryParse(json.Substring(i,e-i),NumberStyles.None,CultureInfo.InvariantCulture,out v)?v:fallback;}
        private static string B64(string s){return Convert.ToBase64String(Encoding.UTF8.GetBytes(s??string.Empty));}private static string FromB64(string s){try{return Encoding.UTF8.GetString(Convert.FromBase64String(s??string.Empty));}catch{return string.Empty;}}
        private static string Normalize(string s){s=(s??string.Empty).Trim();return s.Length<=160?s:s.Substring(0,160);}
    }
}
