using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
namespace AIPort.Server
{
    public sealed class ConversationMemory
    {
        private const int MaximumActiveConversations=128,MaximumRememberedTargets=256,MaximumTurnsPerConversation=8,MaximumRememberedTurnsPerTarget=12,MaximumCharactersPerConversation=6000,MaximumRememberedCharactersPerTarget=9000,MaximumCharactersPerMessage=3000; private const char KeySeparator='\u001f';
        private sealed class Turn{public string Id,PlayerHeroId,TargetInstanceId,PlayerText,NpcText;public DateTime OccurredUtc;public int CharacterCount{get{return PlayerText.Length+NpcText.Length;}}}
        private sealed class Transcript{public readonly Queue<Turn> Turns=new Queue<Turn>();public int CharacterCount;public DateTime LastTouchedUtc;}
        private readonly object gate=new object(); private readonly Dictionary<string,Transcript> active=new Dictionary<string,Transcript>(StringComparer.Ordinal),remembered=new Dictionary<string,Transcript>(StringComparer.Ordinal); private readonly Dictionary<int,string> peerHeroes=new Dictionary<int,string>(); private long revision;
        public long Revision{get{lock(gate)return revision;}}
        public void AdvanceRevision(int amount){if(amount<=0)return;lock(gate)revision+=amount;}
        public void AttachPeer(int peerId,string authoritativePlayerHeroId){string heroId=Normalize(authoritativePlayerHeroId);if(heroId.Length==0)return;lock(gate){string existing;if(peerHeroes.TryGetValue(peerId,out existing)&&string.Equals(existing,heroId,StringComparison.Ordinal))return;ClearPeerLocked(peerId);peerHeroes[peerId]=heroId;}}
        public void ClearPeer(int peerId){lock(gate){peerHeroes.Remove(peerId);ClearPeerLocked(peerId);}}
        public string BuildHistory(int peerId,string playerHeroId,string targetInstanceId,string conversationId){lock(gate){StringBuilder text=new StringBuilder(2048);Transcript prior;if(remembered.TryGetValue(BuildRememberedKey(playerHeroId,targetInstanceId),out prior)&&prior.Turns.Count>0){prior.LastTouchedUtc=DateTime.UtcNow;text.AppendLine("Remembered exchanges from earlier conversations:");AppendTurns(text,prior);}Transcript current;if(active.TryGetValue(BuildActiveKey(peerId,playerHeroId,targetInstanceId,conversationId),out current)&&current.Turns.Count>0){current.LastTouchedUtc=DateTime.UtcNow;if(text.Length>0)text.AppendLine();text.AppendLine("Current conversation:");AppendTurns(text,current);}return text.ToString().TrimEnd();}}
        public int AddTurn(int peerId,string playerHeroId,string targetInstanceId,string conversationId,string playerText,string npcText){string key=BuildActiveKey(peerId,playerHeroId,targetInstanceId,conversationId);Turn turn=new Turn{Id=Guid.NewGuid().ToString("N"),PlayerHeroId=Normalize(playerHeroId),TargetInstanceId=Normalize(targetInstanceId),PlayerText=BoundMessage(playerText),NpcText=BoundMessage(npcText),OccurredUtc=DateTime.UtcNow};lock(gate){Transcript transcript;if(!active.TryGetValue(key,out transcript)){EvictOldestLocked(active,MaximumActiveConversations);transcript=new Transcript();active[key]=transcript;}AddBoundedTurn(transcript,turn,MaximumTurnsPerConversation,MaximumCharactersPerConversation);revision++;return transcript.Turns.Count;}}
        public int ArchiveConversation(int peerId,string playerHeroId,string targetInstanceId,string conversationId){lock(gate){string activeKey=BuildActiveKey(peerId,playerHeroId,targetInstanceId,conversationId);Transcript transcript;if(!active.TryGetValue(activeKey,out transcript))return RememberedCountLocked(playerHeroId,targetInstanceId);active.Remove(activeKey);string rememberedKey=BuildRememberedKey(playerHeroId,targetInstanceId);Transcript memory;if(!remembered.TryGetValue(rememberedKey,out memory)){EvictOldestLocked(remembered,MaximumRememberedTargets);memory=new Transcript();remembered[rememberedKey]=memory;}foreach(Turn turn in transcript.Turns)AddBoundedTurn(memory,turn,MaximumRememberedTurnsPerTarget,MaximumRememberedCharactersPerTarget);return memory.Turns.Count;}}
        public List<PersistentMemoryRecord> ExportPersistentRecords(string playerHeroFilter){lock(gate){Dictionary<string,PersistentMemoryRecord> unique=new Dictionary<string,PersistentMemoryRecord>(StringComparer.Ordinal);Collect(remembered,playerHeroFilter,unique);Collect(active,playerHeroFilter,unique);List<PersistentMemoryRecord> result=new List<PersistentMemoryRecord>(unique.Values);result.Sort((a,b)=>a.OccurredUtc.CompareTo(b.OccurredUtc));return result;}}
        public void ImportPersistentRecords(IList<PersistentMemoryRecord> records){lock(gate){active.Clear();remembered.Clear();peerHeroes.Clear();revision=0;if(records==null)return;foreach(PersistentMemoryRecord r in records){if(r==null)continue;string hero=Normalize(r.PlayerHeroId),target=Normalize(r.TargetInstanceId);if(hero.Length==0||target.Length==0)continue;string key=BuildRememberedKey(hero,target);Transcript t;if(!remembered.TryGetValue(key,out t)){EvictOldestLocked(remembered,MaximumRememberedTargets);t=new Transcript();remembered[key]=t;}Turn turn=new Turn{Id=IsId(r.Id)?r.Id:Guid.NewGuid().ToString("N"),PlayerHeroId=hero,TargetInstanceId=target,PlayerText=BoundMessage(r.PlayerText),NpcText=BoundMessage(r.NpcText),OccurredUtc=r.OccurredUtc.Kind==DateTimeKind.Utc?r.OccurredUtc:r.OccurredUtc.ToUniversalTime()};AddBoundedTurn(t,turn,MaximumRememberedTurnsPerTarget,MaximumRememberedCharactersPerTarget);revision++;}}}
        public void ClearAll(){lock(gate){active.Clear();remembered.Clear();peerHeroes.Clear();revision=0;}}
        private static void Collect(Dictionary<string,Transcript> source,string filter,Dictionary<string,PersistentMemoryRecord> result){foreach(Transcript t in source.Values)foreach(Turn x in t.Turns){if(!string.IsNullOrWhiteSpace(filter)&&!string.Equals(filter,x.PlayerHeroId,StringComparison.Ordinal))continue;result[x.Id]=new PersistentMemoryRecord{Id=x.Id,PlayerHeroId=x.PlayerHeroId,TargetInstanceId=x.TargetInstanceId,PlayerText=x.PlayerText,NpcText=x.NpcText,OccurredUtc=x.OccurredUtc};}}
        private int RememberedCountLocked(string hero,string target){Transcript t;return remembered.TryGetValue(BuildRememberedKey(hero,target),out t)?t.Turns.Count:0;}
        private static bool IsId(string s){if(string.IsNullOrWhiteSpace(s)||s.Length!=32)return false;foreach(char c in s)if(!char.IsDigit(c)&&!(c>='a'&&c<='f')&&!(c>='A'&&c<='F'))return false;return true;}
        private static void AppendTurns(StringBuilder text,Transcript transcript){int index=1;foreach(Turn turn in transcript.Turns){text.Append("Turn ").Append(index++).Append(" Player: ").Append(turn.PlayerText);text.Append(" NPC: ").Append(turn.NpcText).AppendLine();}}
        private static void AddBoundedTurn(Transcript transcript,Turn turn,int maxTurns,int maxCharacters){transcript.Turns.Enqueue(turn);transcript.CharacterCount+=turn.CharacterCount;transcript.LastTouchedUtc=DateTime.UtcNow;while(transcript.Turns.Count>maxTurns||transcript.CharacterCount>maxCharacters){Turn removed=transcript.Turns.Dequeue();transcript.CharacterCount-=removed.CharacterCount;}}
        private void ClearPeerLocked(int peerId){string prefix=peerId.ToString(CultureInfo.InvariantCulture)+KeySeparator;List<string> keys=null;foreach(string key in active.Keys){if(!key.StartsWith(prefix,StringComparison.Ordinal))continue;if(keys==null)keys=new List<string>();keys.Add(key);}if(keys!=null)foreach(string key in keys)active.Remove(key);}
        private static void EvictOldestLocked(Dictionary<string,Transcript> source,int maximum){if(source.Count<maximum)return;string oldestKey=null;DateTime oldest=DateTime.MaxValue;foreach(KeyValuePair<string,Transcript> pair in source){if(pair.Value.LastTouchedUtc>=oldest)continue;oldest=pair.Value.LastTouchedUtc;oldestKey=pair.Key;}if(oldestKey!=null)source.Remove(oldestKey);}
        private static string BuildActiveKey(int peerId,string heroId,string targetInstanceId,string conversationId){return peerId.ToString(CultureInfo.InvariantCulture)+KeySeparator+Normalize(heroId)+KeySeparator+Normalize(targetInstanceId)+KeySeparator+NormalizeConversationId(conversationId);} private static string BuildRememberedKey(string heroId,string targetInstanceId){return Normalize(heroId)+KeySeparator+Normalize(targetInstanceId);} private static string NormalizeConversationId(string value){string n=Normalize(value);return n.Length==0?"default":n;} private static string Normalize(string value){return(value??string.Empty).Trim().Replace(KeySeparator,' ');} private static string BoundMessage(string value){string safe=(value??string.Empty).Trim();return safe.Length<=MaximumCharactersPerMessage?safe:safe.Substring(0,MaximumCharactersPerMessage);}
    }
}
