using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
namespace AIPort.Server
{
    public sealed class DiplomacyProposalPayload{public string ConversationId;public string TargetLeaseId;public string TargetInstanceId;public string Action;}
    public sealed class DiplomacyConfirmPayload{public string IntentId;public string ConversationId;public string TargetLeaseId;public string TargetInstanceId;}
    public sealed class DiplomacyRecipientDecisionPayload{public string StatementId;public string Decision;}
    public sealed class DiplomacyLifecycleCommandPayload{public string StatementId;public string CommitToken;}
    public sealed class DiplomacyStatementDecision{public string IntentId;public string Status;public string ReasonCode;public long StateRevision;public string Action;public string TargetHeroId;public string SourceKingdomId;public string TargetKingdomId;public bool MutationApplied;}
    internal sealed class PendingDiplomacyStatement{public string IntentId;public int PeerId;public string PlayerHeroId;public string CampaignGeneration;public long StateRevision;public string ConversationId;public string TargetLeaseId;public string TargetInstanceId;public string TargetHeroId;public string SourceKingdomId;public string TargetKingdomId;public string Action;public DateTime ExpiresUtc;public bool Confirmed;}
    public sealed class DiplomacyStatementCoordinator
    {
        private const int MaximumRecords=512;private static readonly TimeSpan Lifetime=TimeSpan.FromSeconds(60);
        private static readonly Regex ProposalPattern=new Regex(@"\A{""conversationId"":""([a-f0-9]{32})"",""targetLeaseId"":""([a-f0-9]{32})"",""targetInstanceId"":""([A-Za-z0-9_:.-]{1,320})"",""action"":""(war|peace)"",""reason"":""manual_diplomacy_proposal""}\z",RegexOptions.CultureInvariant);
        private static readonly Regex ConfirmPattern=new Regex(@"\A{""intentId"":""([a-f0-9]{32})"",""conversationId"":""([a-f0-9]{32})"",""targetLeaseId"":""([a-f0-9]{32})"",""targetInstanceId"":""([A-Za-z0-9_:.-]{1,320})"",""reason"":""manual_diplomacy_confirm""}\z",RegexOptions.CultureInvariant);
        private static readonly Regex RecipientDecisionPattern=new Regex(@"\A{""statementId"":""([a-f0-9]{32})"",""decision"":""(accept|reject)"",""reason"":""(?:manual_diplomacy_recipient_decision|map_notification_decision)""}\z",RegexOptions.CultureInvariant);
        private static readonly Regex WithdrawPattern=new Regex(@"\A{""statementId"":""([a-f0-9]{32})"",""reason"":""manual_diplomacy_withdraw""}\z",RegexOptions.CultureInvariant);
        private static readonly Regex NativePreflightPattern=new Regex(@"\A{""statementId"":""([a-f0-9]{32})"",""reason"":""manual_native_(?:war|diplomacy)_preflight""}\z",RegexOptions.CultureInvariant);
        private static readonly Regex NativeCommitPattern=new Regex(@"\A{""statementId"":""([a-f0-9]{32})"",""commitToken"":""([a-f0-9]{32})"",""reason"":""manual_native_war_commit""}\z",RegexOptions.CultureInvariant);
        private static readonly Regex NativePeaceCommitPattern=new Regex(@"\A{""statementId"":""([a-f0-9]{32})"",""commitToken"":""([a-f0-9]{32})"",""reason"":""manual_native_peace_commit""}\z",RegexOptions.CultureInvariant);
        private readonly object gate=new object();private readonly Dictionary<string,DiplomacyStatementDecision> decisions=new Dictionary<string,DiplomacyStatementDecision>(StringComparer.Ordinal);private readonly Queue<string> order=new Queue<string>();private readonly Dictionary<string,PendingDiplomacyStatement> pending=new Dictionary<string,PendingDiplomacyStatement>(StringComparer.Ordinal);
        public static bool TryParseProposal(string json,out DiplomacyProposalPayload payload){payload=null;Match m=ProposalPattern.Match((json??string.Empty).Trim());if(!m.Success)return false;payload=new DiplomacyProposalPayload{ConversationId=m.Groups[1].Value,TargetLeaseId=m.Groups[2].Value,TargetInstanceId=m.Groups[3].Value,Action=m.Groups[4].Value};return true;}
        public static bool TryParseConfirm(string json,out DiplomacyConfirmPayload payload){payload=null;Match m=ConfirmPattern.Match((json??string.Empty).Trim());if(!m.Success)return false;payload=new DiplomacyConfirmPayload{IntentId=m.Groups[1].Value,ConversationId=m.Groups[2].Value,TargetLeaseId=m.Groups[3].Value,TargetInstanceId=m.Groups[4].Value};return true;}
        public static bool TryParseRecipientDecision(string json,out DiplomacyRecipientDecisionPayload payload){payload=null;Match m=RecipientDecisionPattern.Match((json??string.Empty).Trim());if(!m.Success)return false;payload=new DiplomacyRecipientDecisionPayload{StatementId=m.Groups[1].Value,Decision=m.Groups[2].Value};return true;}
        public static bool TryParseWithdraw(string json,out DiplomacyLifecycleCommandPayload payload){payload=null;Match m=WithdrawPattern.Match((json??string.Empty).Trim());if(!m.Success)return false;payload=new DiplomacyLifecycleCommandPayload{StatementId=m.Groups[1].Value,CommitToken=string.Empty};return true;}
        public static bool TryParseNativePreflight(string json,out DiplomacyLifecycleCommandPayload payload){payload=null;Match m=NativePreflightPattern.Match((json??string.Empty).Trim());if(!m.Success)return false;payload=new DiplomacyLifecycleCommandPayload{StatementId=m.Groups[1].Value,CommitToken=string.Empty};return true;}
        public static bool TryParseNativeCommit(string json,out DiplomacyLifecycleCommandPayload payload){payload=null;Match m=NativeCommitPattern.Match((json??string.Empty).Trim());if(!m.Success)return false;payload=new DiplomacyLifecycleCommandPayload{StatementId=m.Groups[1].Value,CommitToken=m.Groups[2].Value};return true;}
        public static bool TryParseNativePeaceCommit(string json,out DiplomacyLifecycleCommandPayload payload){payload=null;Match m=NativePeaceCommitPattern.Match((json??string.Empty).Trim());if(!m.Success)return false;payload=new DiplomacyLifecycleCommandPayload{StatementId=m.Groups[1].Value,CommitToken=m.Groups[2].Value};return true;}
        public DiplomacyStatementDecision Propose(int peerId,string playerHeroId,string requestId,string campaignGeneration,string currentGeneration,long expectedRevision,long currentRevision,DiplomacyProposalPayload payload,string sourceKingdomId,string targetKingdomId,ConversationTargetBinding binding)
        {lock(gate){DiplomacyStatementDecision old;if(decisions.TryGetValue(requestId,out old))return old;string kind=payload==null?string.Empty:payload.Action;if(!Same(campaignGeneration,currentGeneration))return Store(requestId,"rejected","generation_mismatch",currentRevision,kind,string.Empty,sourceKingdomId,targetKingdomId);if(expectedRevision!=0&&expectedRevision!=currentRevision)return Store(requestId,"rejected","stale_revision",currentRevision,kind,string.Empty,sourceKingdomId,targetKingdomId);if(payload==null)return Store(requestId,"rejected","invalid_payload",currentRevision,kind,string.Empty,sourceKingdomId,targetKingdomId);if(binding==null||!binding.IsHero||!Same(binding.PlayerHeroId,playerHeroId))return Store(requestId,"rejected","hero_target_required",currentRevision,kind,string.Empty,sourceKingdomId,targetKingdomId);if(!Same(binding.ConversationId,payload.ConversationId)||!Same(binding.TargetLeaseId,payload.TargetLeaseId)||!Same(binding.TargetInstanceId,payload.TargetInstanceId))return Store(requestId,"rejected","stale_target",currentRevision,kind,binding.TargetId,sourceKingdomId,targetKingdomId);if(string.IsNullOrWhiteSpace(sourceKingdomId)||string.IsNullOrWhiteSpace(targetKingdomId)||Same(sourceKingdomId,targetKingdomId))return Store(requestId,"rejected","kingdom_pair_invalid",currentRevision,kind,binding.TargetId,sourceKingdomId,targetKingdomId);DiplomacyStatementDecision d=Store(requestId,"confirmation_required","player_confirmation_required",currentRevision,kind,binding.TargetId,sourceKingdomId,targetKingdomId);pending[d.IntentId]=new PendingDiplomacyStatement{IntentId=d.IntentId,PeerId=peerId,PlayerHeroId=playerHeroId,CampaignGeneration=currentGeneration,StateRevision=currentRevision,ConversationId=binding.ConversationId,TargetLeaseId=binding.TargetLeaseId,TargetInstanceId=binding.TargetInstanceId,TargetHeroId=binding.TargetId,SourceKingdomId=sourceKingdomId,TargetKingdomId=targetKingdomId,Action=kind,ExpiresUtc=DateTime.UtcNow+Lifetime};return d;}}
        public DiplomacyStatementDecision Confirm(int peerId,string playerHeroId,string requestId,string campaignGeneration,string currentGeneration,long expectedRevision,long currentRevision,DiplomacyConfirmPayload payload,ConversationTargetBinding binding)
        {lock(gate){DiplomacyStatementDecision old;if(decisions.TryGetValue(requestId,out old))return old;if(!Same(campaignGeneration,currentGeneration))return Store(requestId,"rejected","generation_mismatch",currentRevision,string.Empty,string.Empty,string.Empty,string.Empty);if(expectedRevision!=0&&expectedRevision!=currentRevision)return Store(requestId,"rejected","stale_revision",currentRevision,string.Empty,string.Empty,string.Empty,string.Empty);if(payload==null)return Store(requestId,"rejected","invalid_payload",currentRevision,string.Empty,string.Empty,string.Empty,string.Empty);PendingDiplomacyStatement p;if(!pending.TryGetValue(payload.IntentId,out p))return Store(requestId,"rejected","proposal_not_found",currentRevision,string.Empty,string.Empty,string.Empty,string.Empty);if(p.Confirmed)return Store(requestId,"rejected","proposal_already_confirmed",currentRevision,p.Action,p.TargetHeroId,p.SourceKingdomId,p.TargetKingdomId);if(DateTime.UtcNow>p.ExpiresUtc)return Store(requestId,"rejected","confirmation_expired",currentRevision,p.Action,p.TargetHeroId,p.SourceKingdomId,p.TargetKingdomId);if(p.PeerId!=peerId||!Same(p.PlayerHeroId,playerHeroId))return Store(requestId,"rejected","not_authorized",currentRevision,p.Action,p.TargetHeroId,p.SourceKingdomId,p.TargetKingdomId);if(p.StateRevision!=currentRevision)return Store(requestId,"rejected","stale_proposal",currentRevision,p.Action,p.TargetHeroId,p.SourceKingdomId,p.TargetKingdomId);if(binding==null||!Same(payload.ConversationId,p.ConversationId)||!Same(payload.TargetLeaseId,p.TargetLeaseId)||!Same(payload.TargetInstanceId,p.TargetInstanceId)||!Same(binding.ConversationId,p.ConversationId)||!Same(binding.TargetLeaseId,p.TargetLeaseId)||!Same(binding.TargetInstanceId,p.TargetInstanceId))return Store(requestId,"rejected","confirmation_binding_mismatch",currentRevision,p.Action,p.TargetHeroId,p.SourceKingdomId,p.TargetKingdomId);p.Confirmed=true;return Store(requestId,"confirmed_shadow","mutation_suppressed",currentRevision,p.Action,p.TargetHeroId,p.SourceKingdomId,p.TargetKingdomId);}}
        private DiplomacyStatementDecision Store(string requestId,string status,string reason,long revision,string action,string targetHero,string source,string target){DiplomacyStatementDecision d=new DiplomacyStatementDecision{IntentId=Guid.NewGuid().ToString("N"),Status=status,ReasonCode=reason,StateRevision=revision,Action=action??string.Empty,TargetHeroId=targetHero??string.Empty,SourceKingdomId=source??string.Empty,TargetKingdomId=target??string.Empty,MutationApplied=false};decisions[requestId]=d;order.Enqueue(requestId);while(order.Count>MaximumRecords)decisions.Remove(order.Dequeue());return d;}
        private static bool Same(string a,string b){return string.Equals(a??string.Empty,b??string.Empty,StringComparison.Ordinal);}
    }
}
