using System;using System.Collections.Generic;
namespace AIPort.Server
{
    public sealed class NativeWarCommitLease{public string Token;public int PeerId;public string PlayerHeroId;public string StatementId;public string Action;public string CampaignGeneration;public long StateRevision;public string SourceFactionId;public string TargetFactionId;public DateTime ExpiresUtc;public bool Consumed;}
    public sealed class NativeWarCommitLeaseRegistry
    {
        private const int MaximumLeases=256;private static readonly TimeSpan Lifetime=TimeSpan.FromSeconds(60);private readonly object gate=new object();private readonly Dictionary<string,NativeWarCommitLease> byToken=new Dictionary<string,NativeWarCommitLease>(StringComparer.Ordinal);private readonly Queue<string> order=new Queue<string>();
        public NativeWarCommitLease Issue(int peerId,string playerHeroId,string statementId,string generation,long revision,string sourceFactionId,string targetFactionId,DateTime utc){return Issue(peerId,playerHeroId,statementId,"war",generation,revision,sourceFactionId,targetFactionId,utc);}
        public NativeWarCommitLease Issue(int peerId,string playerHeroId,string statementId,string action,string generation,long revision,string sourceFactionId,string targetFactionId,DateTime utc){lock(gate){string token=Guid.NewGuid().ToString("N");NativeWarCommitLease l=new NativeWarCommitLease{Token=token,PeerId=peerId,PlayerHeroId=playerHeroId??string.Empty,StatementId=statementId??string.Empty,Action=NormalizeAction(action),CampaignGeneration=generation??string.Empty,StateRevision=revision,SourceFactionId=sourceFactionId??string.Empty,TargetFactionId=targetFactionId??string.Empty,ExpiresUtc=Utc(utc)+Lifetime};byToken[token]=l;order.Enqueue(token);while(order.Count>MaximumLeases)byToken.Remove(order.Dequeue());return l;}}
        public bool TryConsume(string token,int peerId,string playerHeroId,string statementId,string generation,long revision,string sourceFactionId,string targetFactionId,DateTime utc,out NativeWarCommitLease lease,out string reason){return TryConsume(token,peerId,playerHeroId,statementId,"war",generation,revision,sourceFactionId,targetFactionId,utc,out lease,out reason);}
        public bool TryConsume(string token,int peerId,string playerHeroId,string statementId,string action,string generation,long revision,string sourceFactionId,string targetFactionId,DateTime utc,out NativeWarCommitLease lease,out string reason){lock(gate){lease=null;reason="native_diplomacy_commit_not_found";NativeWarCommitLease l;if(!byToken.TryGetValue(token??string.Empty,out l))return false;lease=l;if(l.Consumed){reason="native_diplomacy_commit_consumed";return false;}l.Consumed=true;if(Utc(utc)>l.ExpiresUtc){reason="native_diplomacy_commit_expired";return false;}if(l.PeerId!=peerId||!Same(l.PlayerHeroId,playerHeroId)||!Same(l.StatementId,statementId)||!Same(l.Action,NormalizeAction(action))){reason="native_diplomacy_commit_not_authorized";return false;}if(!Same(l.CampaignGeneration,generation)){reason="generation_mismatch";return false;}if(l.StateRevision!=revision){reason="stale_revision";return false;}if(!Same(l.SourceFactionId,sourceFactionId)||!Same(l.TargetFactionId,targetFactionId)){reason="stale_faction_pair";return false;}reason="native_diplomacy_commit_consumed";return true;}}
        public int RemovePeer(int peerId){lock(gate){int n=0;foreach(NativeWarCommitLease l in byToken.Values)if(l.PeerId==peerId&&!l.Consumed){l.Consumed=true;n++;}return n;}}
        public void Clear(){lock(gate){byToken.Clear();order.Clear();}}
        private static string NormalizeAction(string value){value=(value??string.Empty).Trim().ToLowerInvariant();return value=="peace"?"peace":"war";}
        private static DateTime Utc(DateTime d){return d.Kind==DateTimeKind.Utc?d:d.ToUniversalTime();}private static bool Same(string a,string b){return string.Equals(a??string.Empty,b??string.Empty,StringComparison.Ordinal);}
    }
}
