using System;using System.Collections.Generic;
namespace AIPort.Server
{
 public sealed class NativeDiplomacyCommitJournal
 {
  private const int MaximumRecords=256,MaximumPerPairPerHour=2;private readonly object gate=new object();private readonly Dictionary<string,PersistentNativeDiplomacyCommitRecord> byId=new Dictionary<string,PersistentNativeDiplomacyCommitRecord>(StringComparer.Ordinal);private readonly Queue<string> order=new Queue<string>();
  public int Count{get{lock(gate)return byId.Count;}}
  public bool TryPrepare(string statementId,string action,string sourceHeroId,string targetHeroId,string sourceFactionId,string targetFactionId,string generation,long revision,DateTime utc,out PersistentNativeDiplomacyCommitRecord record,out string reason,out bool fresh)
  {lock(gate){record=null;reason="native_journal_invalid";fresh=false;string kind=Action(action),pair=Pair(sourceFactionId,targetFactionId);DateTime now=Utc(utc),cutoff=now.AddHours(-1);int recent=0;foreach(PersistentNativeDiplomacyCommitRecord r in byId.Values){if(Same(r.StatementId,statementId)&&Same(r.Action,kind)){record=r;reason=IsFinal(r.Phase)?"native_journal_final_replay":"native_journal_active_replay";return true;}if(Pair(r.SourceFactionId,r.TargetFactionId)!=pair)continue;if(!IsFinal(r.Phase)){reason="native_journal_pair_active";return false;}if(r.PreparedUtc>=cutoff)recent++;}if(!Id(statementId)||kind.Length==0||Empty(sourceHeroId)||Empty(targetHeroId)||Empty(sourceFactionId)||Empty(targetFactionId)||sourceFactionId==targetFactionId||Empty(generation)){return false;}if(recent>=MaximumPerPairPerHour){reason="native_journal_pair_rate_limit";return false;}record=new PersistentNativeDiplomacyCommitRecord{Id=Guid.NewGuid().ToString("N"),StatementId=statementId,Action=kind,SourceHeroId=B(sourceHeroId,160),TargetHeroId=B(targetHeroId,160),SourceFactionId=B(sourceFactionId,160),TargetFactionId=B(targetFactionId,160),CampaignGeneration=B(generation,64),PreparedRevision=revision,Phase="prepared",PreparedUtc=now,UpdatedUtc=now,ReasonCode="native_commit_prepared",NativeMutationApplied=false,AtWarObserved=false};byId[record.Id]=record;order.Enqueue(record.Id);while(order.Count>MaximumRecords)byId.Remove(order.Dequeue());fresh=true;reason="native_commit_prepared";return true;}}
  public bool TryTransition(string id,string nextPhase,DateTime utc,string reason,bool nativeMutationApplied,bool atWarObserved,out PersistentNativeDiplomacyCommitRecord record,out string failure)
  {lock(gate){record=null;failure="native_journal_not_found";PersistentNativeDiplomacyCommitRecord r;if(!byId.TryGetValue(id??string.Empty,out r))return false;record=r;string next=Phase(nextPhase);if(next.Length==0){failure="native_journal_phase_invalid";return false;}if(Same(r.Phase,next)){failure="native_journal_idempotent_transition";return true;}if(!Allowed(r.Phase,next)){failure="native_journal_transition_rejected";return false;}r.Phase=next;r.UpdatedUtc=Utc(utc);r.ReasonCode=B(reason,96);r.NativeMutationApplied=r.NativeMutationApplied||nativeMutationApplied;r.AtWarObserved=atWarObserved;failure="native_journal_transitioned";return true;}}
  public bool TryGet(string id,out PersistentNativeDiplomacyCommitRecord record){lock(gate)return byId.TryGetValue(id??string.Empty,out record);}
  public List<PersistentNativeDiplomacyCommitRecord> Recoverable(){lock(gate){List<PersistentNativeDiplomacyCommitRecord> x=new List<PersistentNativeDiplomacyCommitRecord>();foreach(string id in order){PersistentNativeDiplomacyCommitRecord r;if(byId.TryGetValue(id,out r)&&(r.Phase=="prepared"||r.Phase=="applying"||r.Phase=="applied"||r.Phase=="recovery_required"))x.Add(r);}return x;}}
  public List<PersistentNativeDiplomacyCommitRecord> Export(){lock(gate){List<PersistentNativeDiplomacyCommitRecord>x=new List<PersistentNativeDiplomacyCommitRecord>();foreach(string id in order){PersistentNativeDiplomacyCommitRecord r;if(byId.TryGetValue(id,out r))x.Add(r);}return x;}}
  public void Import(IList<PersistentNativeDiplomacyCommitRecord> records){lock(gate){byId.Clear();order.Clear();if(records==null)return;foreach(PersistentNativeDiplomacyCommitRecord r in records){if(r==null||!Id(r.Id)||!Id(r.StatementId)||Action(r.Action).Length==0||Phase(r.Phase).Length==0||Empty(r.SourceHeroId)||Empty(r.TargetHeroId)||Empty(r.SourceFactionId)||Empty(r.TargetFactionId)||Same(r.SourceFactionId,r.TargetFactionId)||Empty(r.CampaignGeneration))continue;r.Action=Action(r.Action);r.Phase=Phase(r.Phase);r.SourceHeroId=B(r.SourceHeroId,160);r.TargetHeroId=B(r.TargetHeroId,160);r.SourceFactionId=B(r.SourceFactionId,160);r.TargetFactionId=B(r.TargetFactionId,160);r.CampaignGeneration=B(r.CampaignGeneration,64);r.ReasonCode=B(r.ReasonCode,96);byId[r.Id]=r;order.Enqueue(r.Id);while(order.Count>MaximumRecords)byId.Remove(order.Dequeue());}}}
  public void Clear(){lock(gate){byId.Clear();order.Clear();}}
  private static bool Allowed(string a,string b){return a=="prepared"&&(b=="applying"||b=="aborted"||b=="failed")||a=="applying"&&(b=="applied"||b=="verified"||b=="failed"||b=="recovery_required")||a=="applied"&&(b=="verified"||b=="recovery_required"||b=="failed")||a=="recovery_required"&&(b=="verified"||b=="failed");}
  private static bool IsFinal(string p){return p=="verified"||p=="failed"||p=="aborted";}
  private static string Action(string s){s=(s??string.Empty).Trim().ToLowerInvariant();return s=="war"||s=="peace"?s:string.Empty;}private static string Phase(string s){s=(s??string.Empty).Trim().ToLowerInvariant();return s=="prepared"||s=="applying"||s=="applied"||s=="verified"||s=="failed"||s=="recovery_required"||s=="aborted"?s:string.Empty;}
  private static string Pair(string a,string b){return string.CompareOrdinal(a??string.Empty,b??string.Empty)<=0?(a??string.Empty)+""+(b??string.Empty):(b??string.Empty)+""+(a??string.Empty);}private static bool Same(string a,string b){return string.Equals(a??string.Empty,b??string.Empty,StringComparison.Ordinal);}private static bool Empty(string s){return string.IsNullOrWhiteSpace(s);}private static string B(string s,int n){s=(s??string.Empty).Trim();return s.Length<=n?s:s.Substring(0,n);}private static DateTime Utc(DateTime d){return d.Kind==DateTimeKind.Utc?d:d.ToUniversalTime();}private static bool Id(string s){if(string.IsNullOrWhiteSpace(s)||s.Length!=32)return false;foreach(char c in s)if(!char.IsDigit(c)&&!(c>='a'&&c<='f')&&!(c>='A'&&c<='F'))return false;return true;}
 }
}
